/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package big.number.calculator;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.LinkedList;

/**
 *
 * @author Porya
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    String a;
    String b;

    String sm = "";

    int c = 0;

    LinkedList<Integer> x;
    LinkedList<Integer> y;

    boolean signx = false;
    boolean signy = false;

    LinkedList<Integer> d;

    LinkedList<Integer> sum;

    boolean sign = false;

    public NewJFrame() {
        initComponents();
        

        x = new LinkedList<>();
        y = new LinkedList<>();
        sum = new LinkedList<>();
        d = new LinkedList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("A:");

        jLabel2.setText("B:");

        jLabel3.setText("Design & Programmed By: Porya Gohary");

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(1);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setText("Sum:");

        jButton2.setText("*");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("C");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("-");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("/");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jTextField1))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4))
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Stex();
        int k;
        k = bigger((LinkedList< Integer>) x.clone(), (LinkedList< Integer>) y.clone());

        if (signx && signy) {
            add(x, y);
            //System.out.println(sum.toString());
        }

        if (!signx && !signy) {
            add(x, y);
            sum.add(-1);
        } else if (signx && !signy) {
            if (k == 2) {
                sub((LinkedList< Integer>) y.clone(), (LinkedList< Integer>) x.clone());
                sum.add(-1);
            }
            if (k == 1) {
                sub((LinkedList< Integer>) x.clone(), (LinkedList< Integer>) y.clone());
            }

            if (k == 0) {
                sum.add(0);
            }
        } else if (!signx && signy) {
            if (k == 2) {
                sub((LinkedList< Integer>) y.clone(), (LinkedList< Integer>) x.clone());
                //sum.add(-1);
            }
            if (k == 1) {
                sub((LinkedList< Integer>) x.clone(), (LinkedList< Integer>) y.clone());
                sum.add(-1);
            }

            if (k == 0) {
                sum.add(0);
            }
        }

        print();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Stex();
        
        beat();
        if((signx&&!signy)||(!signx&&signy) ){
            sum.add(-1);
        }
        
        print();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        x.clear();
        y.clear();
        sum.clear();
        c = 0;
        sign = false;

        jTextField1.setText("");
        jTextField2.setText("");

        jTextArea1.setText("");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Stex();
        int k;
        k = bigger((LinkedList< Integer>) x.clone(), (LinkedList< Integer>) y.clone());

        if(signx&&signy){
         if(k==1)
            sub(x, y);
         if(k==2){
             sub(y, x);
             sum.add(-1);
         }
         if(k==0)
             sum.add(0);
         
        }
        
        if(signx&&!signy){
            add(x,y);
        }
        
        if(!signx&&signy){
            add(x,y);
            sum.add(-1);
        }
        
        if(!signx&&!signy){
            if(k==1){
                sub(x,y);
                sum.add(-1);
            }
            if(k==2){
                sub(y,x);
            }
        }
        
        
        print();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Stex();
        div(x, y);
        print();

    }//GEN-LAST:event_jButton5ActionPerformed
    ///////////////SHOW RESULT\\\\\\\\\\\\\

    public void print() {
        sm = "";
        int j;

        while (!sum.isEmpty()) {
            j = sum.pollLast();
            if (j != -1) {
                sm += j;
            } else {
                sm += "-";
            }
        }

        jTextArea1.setText(sm);

    }

    public void Stex() {
        a = jTextField1.getText();
        b = jTextField2.getText();

        System.out.println(a.charAt(0));

        if (Character.isDigit(a.charAt(0))) {
            signx = true;
            for (int i = a.length() - 1; i >= 0; i--) {

                x.add(Integer.parseInt(Character.toString(a.charAt(i))));

            }

        } else if ("+".equals(Character.toString(a.charAt(0)))) {

            signx = true;
            for (int i = a.length() - 1; i >= 1; i--) {

                x.add(Integer.parseInt(Character.toString(a.charAt(i))));

            }

        } else {
            signx = false;

            for (int i = a.length() - 1; i >= 1; i--) {

                x.add(Integer.parseInt(Character.toString(a.charAt(i))));

            }

        }

        if (Character.isDigit(b.charAt(0))) {
            signy = true;
            for (int i = b.length() - 1; i >= 0; i--) {

                y.add(Integer.parseInt(Character.toString(b.charAt(i))));

            }

        } else if ("+".equals(Character.toString(b.charAt(0)))) {

            signy = true;
            for (int i = b.length() - 1; i >= 1; i--) {

                y.add(Integer.parseInt(Character.toString(b.charAt(i))));

            }

        } else {
            signy = false;
            for (int i = b.length() - 1; i >= 1; i--) {

                y.add(Integer.parseInt(Character.toString(b.charAt(i))));

            }

        }

    }

    public int bigger(LinkedList<Integer> x, LinkedList<Integer> y) {
        int t = 0;
        if (x.size() > y.size()) {
            return 1;
        }
        if (x.size() < y.size()) {
            return 2;
        }

        if (x.size() == y.size()) {

            while (!x.isEmpty()) {
                t = x.pollLast() - y.pollLast();
                //System.out.println(t);
                if (t > 0) {
                    return 1;
                }

                if (t < 0) {
                    return 2;
                }

            }

            return 0;
        }
        return 0;

    }

    ///////////////ADD\\\\\\\\\\\\\
    public void add(LinkedList<Integer> x, LinkedList<Integer> y) {
        while (!x.isEmpty() || !y.isEmpty()) {
            if (!x.isEmpty()) {
                c += x.poll();

            }

            if (!y.isEmpty()) {
                c += y.poll();

            }

            sum.add(c % 10);
            c /= 10;
        }

        if (c != 0) {
            sum.add(c);
        }

    }

    ///////////////SUBTRACKT\\\\\\\\\\\\\
    public void sub(LinkedList<Integer> x, LinkedList<Integer> y) {
        c = 0;
        //System.out.println(x.get(0) + "");
        System.out.println(x.toString() + "    " + y.toString());

        while (!x.isEmpty()) {
            if (!y.isEmpty()) {
                c += x.poll() - y.poll();
            } else {
                c += x.poll();
                if (c < 0) {
                    sum.add(c + 10);
                    c = -1;
                } else {
                    sum.add(c);
                    c = 0;
                }
                continue;
            }

            if (c < 0) {
                sum.add(c + 10);
                c = -1;
            } else {
                sum.add(c);
                c = 0;
            }

        }
        if (c != 0) {
            sign = true;
        }
    }

    ///////////////BEAT\\\\\\\\\\\\\
    public void beat() {

        LinkedList<Integer> t = new LinkedList<>();
        LinkedList<Integer> g = new LinkedList<>();
        c = 0;
        //System.out.println(x.size()+"        "+y.size());

        for (int i = 0; i < y.size(); i++) {

            for (int j = 0; j < i; j++) {
                t.add(0);
            }
            for (int j = 0; j < x.size(); j++) {
                c += x.get(j) * y.get(i);
                //System.out.println(c);
                t.add(c % 10);

                c /= 10;

            }
            if (c != 0) {
                t.add(c);
            }

            //System.out.println(t.toString());
            c = 0;
            add(t, g);

            g = (LinkedList<Integer>) sum.clone();
            //System.out.println(g.toString()+"      "+sum.toString());
            sum.clear();

            t.clear();

        }
        sum = g;

    }

    ///////////////DIVIDE\\\\\\\\\\\\\
    public void div(LinkedList<Integer> x, LinkedList<Integer> y) {
        LinkedList<Integer> t = new LinkedList<>();
        d.clear();
        t.add(1);
        d.add(0);

        LinkedList<Integer> h = new LinkedList<>();
        while (!sign) {

            //System.out.println(d.toString()+"");
            sum.clear();
            sub((LinkedList<Integer>) x.clone(), (LinkedList<Integer>) y.clone());

            //System.out.println(sum.toString());
            x.clear();
            x = (LinkedList<Integer>) sum.clone();
            sum.clear();

            add((LinkedList<Integer>) d.clone(), (LinkedList<Integer>) t.clone());
            d = (LinkedList<Integer>) sum.clone();

            System.out.println(d.toString());

            sum.clear();
            //System.out.println(sum.toString());
        }
        sum = (LinkedList<Integer>) d.clone();
        
        if(!signx&&signy)
            sum.add(-1);
        else if(signx&&!signy)
            sum.add(-1);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables


}
